UV := $(shell command -v uv 2> /dev/null)

.PHONY: uvcheck install lint format benchcheck bench benchpreview regressions clean

# Extra arguments for local asv runs, e.g. make bench BENCH_ARGS="--quick -b bench_ffts"
BENCH_ARGS ?=
# Local checkout of pylops benchmarked by `make bench` (installed in editable mode)
PYLOPS_REPO ?= ../pylops
# Configuration used by local asv runs (generated by ci/local_conf.py)
ASV_LOCAL_CONF := .asv/asv.local.conf.json
# Port used by `asv preview`
ASV_PORT ?= 8765
# Extra arguments for `make regressions`, e.g. make regressions REPORT_ARGS="--threshold 1.3"
REPORT_ARGS ?=

uvcheck:
ifndef UV
	$(error "Ensure uv is in your PATH")
endif
	@echo Using uv: $(UV)

install:
	# Create the virtual environment with asv, ruff and the latest pylops release
	make uvcheck
	$(UV) sync --locked

lint:
	# Run ruff linter and formatter (check only) on the benchmark suite
	make uvcheck
	$(UV) run ruff check . && $(UV) run ruff format --check .

format:
	# Apply ruff fixes and formatting to the benchmark suite
	make uvcheck
	$(UV) run ruff check --fix . && $(UV) run ruff format .

benchcheck:
	# Validate the asv benchmark suite (imports only, no benchmark is executed)
	make uvcheck
	$(UV) run asv check -E existing

bench:
	# Run the asv benchmarks locally against $(PYLOPS_REPO) installed in editable mode
	# (results in .asv/results-local, never uploaded; the GitHub Actions run published at
	# https://pylops.github.io/pylops-asv/ is the reference)
	make uvcheck
	$(UV) pip install -e $(PYLOPS_REPO) && \
	PYLOPS_REPO=$(PYLOPS_REPO) $(UV) run --no-sync python ci/local_conf.py && \
	$(UV) run --no-sync asv machine --yes && \
	$(UV) run --no-sync asv run --config $(ASV_LOCAL_CONF) --python=same \
	--set-commit-hash $$(git -C $(PYLOPS_REPO) rev-parse HEAD) --show-stderr $(BENCH_ARGS)

benchpreview:
	# Build and serve the asv website from local results
	make uvcheck
	$(UV) run --no-sync asv publish --config $(ASV_LOCAL_CONF) && \
	$(UV) run --no-sync asv preview --config $(ASV_LOCAL_CONF) --port $(ASV_PORT)

regressions:
	# Report worrying regressions in the committed results, as the weekly
	# PyLops-regressions workflow does in its run summary (no benchmark is executed)
	python3 ci/regression_report.py --repo $(PYLOPS_REPO) $(REPORT_ARGS)

clean:
	# Remove local asv environments, results and html
	rm -rf .asv
